/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chocopy;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testHello() {
        App.runSimpleInterpreter("src/test/python/hello.py");
    }
}
